### ISSUE TITLE
Excellent Project

### ISSUE THREAD

**Issue by teknium1** [CogStack/OpenGPT#3]
I was thinking of exactly this sort of method just a day or two ago! I'm glad to see it formalized and proven out.

Are you all interested in working on more? If you'd like to collaborate, let me know!

**Comment by teknium1** [comment]
Also can I ask, was there worse outputs when you included the context in the task generating prompt? It seems to be the one that doesnt seem to utilize it

**Comment by w-is-h** [comment]
Hi @teknium1 , thank you. We are open to collaborations, the project is open-source so any kind of contribution is welcome. 

Regarding the second question - when writing prompts with context the only problem was we had to be much more careful, and designing the prompt was harder.  The prompt without context, was just there for comparison. Usually, if the context is good, the prompts with context give better results.

**Comment by teknium1** [comment]
> Hi @teknium1 , thank you. We are open to collaborations, the project is open-source so any kind of contribution is welcome.
> 
> Regarding the second question - when writing prompts with context the only problem was we had to be much more careful, and designing the prompt was harder. The prompt without context, was just there for comparison. Usually, if the context is good, the prompts with context give better results.

Perhaps we can ask GPT4 to rate the quality of what it makes from the text chunk given and can exclude what it thinks is bad from final dataset. People seem impressed by GPT4-Evals (though I'm not yet convinced), so maybe it can determine if a given text chunk is valid for doing any of the dataset creation with. Then, while more costly, you could pipe in raw data without extensive cleaning and judging processes.

**Comment by w-is-h** [comment]
I'm not a big fan of using GPT-4 to eval the quality, based on what I've seen it tends to prefer a certain writing style and you end up with a dataset that is not very diverse. 

The main challenge is in fact the question/task, not the answer, given a context the answers tend to always be very good (correct). So the problem is how to create a diverse set of tasks that you can use to prompt the model to generate answers/solutions. My idea was, given a context (or many of them) create a large dataset of tasks, then embed each task using the embedding API from OpenAI, remove similar tasks and keep only a very diverse dataset of tasks. Then use those with different contexts to generate answers/solutions. Could be something we should test.

**Comment by teknium1** [comment]
Another thing to expand into different fields is somehow make this line in your prompt either variable (based on domain of the text to transform), or have GPT4 generate who or what style it should be writing it as:

```
Create a conversation between a Patient concerned about the symptoms and disorders presented above and an AI-Assistant. The conversation should abide by the following rules and instructions:  
```  

However, this is only very important if you collect a very diverse set of raw text for different domains

**Comment by w-is-h** [comment]
An interesting prompt I've been testing is (abbreviated version below, will add the full one to the prompts.json):
```
{context}
-------
Given the context above generate a set of diverse tasks (MCQ, Q/A, imperative instructions, conversations, etc.) and solutions. 

List of 10 tasks/solutions:
```

In this way, gpt-4 will create a wide variety of tasks, specific to the provided context.

**Comment by teknium1** [comment]
One prompt to rule them all? ^_^
